### ISSUE TITLE
Если маяк уже с таким именем существует, то всё равно, ошибочно выводится сообщение что пользователь его зажёг, в дополнение к первому сообщению о том, что этого сделать невозможно.

### ISSUE THREAD

**Issue by alloploha** [alloploha/Beacons-DiscordBot#3]
![image](https://user-images.githubusercontent.com/80926732/113498772-f855fc00-94dd-11eb-9ebf-2b2d9fee9770.png)

https://github.com/alloploha/Beacons-DiscordBot/blob/d3c945496e6f39ad4dd24177a8a5ab7b9fd57e3a/BeaconsBot.py#L47-L61

**Comment by adenworker** [comment]
#9
